version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./data:/data
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: